version: "3.8"
services:
  cckl-app:
    container_name: cckl-website
    build:
      context:  .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true